### ISSUE TITLE
Pairing with Philips Hue and Homebridge fails

### ISSUE THREAD

**Issue by stefanwichmann** [mctofu/homekit#8]
I'm testing out your library to control my Homekit accessories. Sadly pairing with the two bridges in my setup fails with different errors.

Discovery:

> ./homekit discover                                                      
> Detected Device: Homebridge\ E8A4
> Model: homebridge
> ID: CC:24:3D:E3:CE:30
> IPs: [192.168.0.79 fe80::3c5c:64c3:a559:c516 2a04:4540:653a:7800:2d2f:7343:d504:3c84 fd00::83e:7c3b:ae33:ac5f]
> Port: 51826
> Feature flags: No support for HAP Pairing (0)
> Status flags: Accessory is paired (0)
>
> Detected Device: Philips\ hue\ -\ 412EFC
> Model: BSB002
> ID: 09:8A:EA:4E:AF:54
> IPs: [192.168.0.22 2a04:4540:653a:7800:217:88ff:fe41:2efc fd54:c6d6:517::1 fd00::217:88ff:fe41:2efc fe80::217:88ff:fe41:2efc]
> Port: 8080
> Feature flags: Supports HAP Pairing (1)
> Status flags: Accessory is paired (0)
> 
> Found 2 devices

Pairing attempt with Homebridge:
> ./homekit pair --id CC:24:3D:E3:CE:30 --pin XXX-XX-XXX --name homebridge
> INFO 2020/10/22 10:46:45 setup_client_controller.go:58: Max Authentication Attempts
> panic: Max Authentication Attempts
> 
> goroutine 1 [running]:
> log.(*Logger).Panic(0xc0001ac140, 0xc000239700, 0x1, 0x1)
> 	/usr/local/Cellar/go/1.15.2/libexec/src/log/log.go:221 +0xac
> github.com/brutella/hc/hap/pair.(*SetupClientController).Handle(0xc0000aa840, 0x15ed9a0, 0xc0000aad20, 0x2, 0x0, 0x0, 0x1f80998)
> 	/Users/stefan/Development/go/pkg/mod/github.com/brutella/hc@v1.2.2/hap/pair/setup_client_controller.go:58 +0xca
> github.com/brutella/hc/hap/pair.HandleReaderForHandler(0x15e1d00, 0xc0000aacf0, 0x15e1f60, 0xc0000aa840, 0x24, 0xc0000ee000, 0x6, 0x600)
> 	/Users/stefan/Development/go/pkg/mod/github.com/brutella/hc@v1.2.2/hap/pair/handler.go:20 +0x13b
> github.com/mctofu/homekit/client.(*SetupClient).Pair(0xc000239b78, 0x15ead60, 0xc00019c008, 0xc000239bd8, 0xc000239c10, 0xc0000d6060, 0x0, 0x0)
> 	/Users/stefan/Development/go/src/github.com/mctofu/homekit/client/setup.go:59 +0x655
> github.com/mctofu/homekit/cmd/homekit/cli.pair(0x15ead60, 0xc00019c008, 0xc0001946c0, 0x38, 0x154e632, 0x7, 0x7ffeefbffa7c, 0x11, 0x7ffeefbffa94, 0xa, ...)
> 	/Users/stefan/Development/go/src/github.com/mctofu/homekit/cmd/homekit/cli/pair.go:65 +0x62c
> github.com/mctofu/homekit/cmd/homekit/cli.pairCmd.func1(0x15ead60, 0xc00019c008, 0xc0001946c0, 0x38, 0x154e632, 0x7, 0xc0001efd18, 0xc0001efcf0)
> 	/Users/stefan/Development/go/src/github.com/mctofu/homekit/cmd/homekit/cli/pair.go:30 +0xb2
> github.com/mctofu/homekit/cmd/homekit/cli.configCommandRunner.func1(0xc0001d1080, 0xc000198d80, 0x0, 0x6, 0x0, 0x0)
> 	/Users/stefan/Development/go/src/github.com/mctofu/homekit/cmd/homekit/cli/cli.go:76 +0x102
> github.com/spf13/cobra.(*Command).execute(0xc0001d1080, 0xc000198d20, 0x6, 0x6, 0xc0001d1080, 0xc000198d20)
> 	/Users/stefan/Development/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850 +0x47c
> github.com/spf13/cobra.(*Command).ExecuteC(0x18acd20, 0xc0001d1340, 0xc0001d0dc0, 0xc0001d0b00)
> 	/Users/stefan/Development/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
> github.com/spf13/cobra.(*Command).Execute(...)
> 	/Users/stefan/Development/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
> github.com/spf13/cobra.(*Command).ExecuteContext(...)
> 	/Users/stefan/Development/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:888
> github.com/mctofu/homekit/cmd/homekit/cli.Execute(0xc0001eff48, 0x10463ea)
> 	/Users/stefan/Development/go/src/github.com/mctofu/homekit/cmd/homekit/cli/cli.go:40 +0x53
> main.main()
> 	/Users/stefan/Development/go/src/github.com/mctofu/homekit/cmd/homekit/main.go:11 +0x26

Pairing attempt with the Philips Hue bridge:
> ./homekit pair --id 09:8A:EA:4E:AF:54 --pin XXX-XX-XXX --name hue
> Error: pair: pairStartRequest: invalid status code 429
> Usage:
>   homekit pair [flags]
> 
> Flags:
>       --configPath string   Directory to store controller configs. (default "/Users/stefan/Library/Application Support/mctofu/homekit")
>       --controller string   Name of controller profile to use. (default "default")
>   -h, --help                help for pair
>       --id string           Device id of accessory to pair (from discovery)
>   -n, --name string         Alias to reference accessory by
>       --pin string          Accessory PIN for pairing (XXX-XX-XXX)
> 
> pair: pairStartRequest: invalid status code 429

Any hints on what's wrong?

**Comment by stefanwichmann** [comment]
The issue was an already existing pairing with another controller. Never mind :-)
